// AUTO-GENERATED by scripts/gen-agon-icons.mjs — DO NOT EDIT
import React from "react";

const PATHS: Record<string, string> = {
  "accueil": "<path d=\"M3 9L12 4L21 9Z\"/><path d=\"M6.5 11.5V17.5M10.5 11.5V17.5M13.5 11.5V17.5M17.5 11.5V17.5M3 20H21\"/>",
  "alerte": "<path d=\"M12 3.5L21.5 20H2.5Z\"/><path d=\"M12 9.5V14\"/><circle cx=\"12\" cy=\"16.9\" r=\".9\" fill=\"currentColor\" stroke=\"none\"/>",
  "athlete": "<circle cx=\"12\" cy=\"7\" r=\"3.5\"/><path d=\"M5 21V19A7 7 0 0 1 19 19V21\"/>",
  "balance": "<path d=\"M12 4V20M8 20H16M5 7H19M5 7L2 12.5M5 7L8 12.5M19 7L16 12.5M19 7L22 12.5\"/><path d=\"M2 12.5A3 3 0 0 0 8 12.5ZM16 12.5A3 3 0 0 0 22 12.5Z\"/>",
  "barre": "<path d=\"M3 12H21M6 7V17M9 9V15M15 9V15M18 7V17\"/>",
  "biometrie": "<rect x=\"2.5\" y=\"8\" width=\"19\" height=\"8\"/><path d=\"M6.5 8V12M10.5 8V11M14.5 8V12M18.5 8V11\"/>",
  "calendrier": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15.5\"/><path d=\"M3.5 10H20.5M8 3V7M16 3V7M7 14H9M11 14H13M15 14H17M7 17.5H9M11 17.5H13\"/>",
  "cerveau": "<path d=\"M12 5C10 3.5 6.5 4.5 6.5 8C4.5 9 4.5 13 6.5 14C6.5 17.5 10 19 12 18.5C14 19 17.5 17.5 17.5 14C19.5 13 19.5 9 17.5 8C17.5 4.5 14 3.5 12 5ZM12 5V18.5\"/><path d=\"M8.5 9.5H10M14 9.5H15.5M8 14H10M14 14H16\"/>",
  "chrono": "<circle cx=\"12\" cy=\"13.5\" r=\"7.5\"/><path d=\"M10 3H14M12 3V6M12 10V13.5H15\"/>",
  "cloche": "<path d=\"M6 17V11A6 6 0 0 1 18 11V17M4 17H20M12 3V5M10 20H14\"/>",
  "coach": "<rect x=\"5\" y=\"4\" width=\"14\" height=\"17\"/><path d=\"M9 4V2.5H15V4M8.5 9H15.5M8.5 13H15.5M8.5 17H12\"/>",
  "commentaire": "<path d=\"M4 5H20V16H10L6 20V16H4Z\"/><path d=\"M8 9H16M8 12.5H13\"/>",
  "competition": "<circle cx=\"12\" cy=\"15.5\" r=\"5\"/><path d=\"M8.6 11.8L5 3H9L12 9.5L15 3H19L15.4 11.8\"/>",
  "corbeille": "<path d=\"M4 7H20M9 7V4H15V7M6 7L7 21H17L18 7M10 11V17M14 11V17\"/>",
  "courbatures": "<path d=\"M13 3H17L18.5 5.5L17.5 8L20 15C20 18.5 17.5 20.5 14.5 20.5H3.5V15L7 13.5C7.5 10 12.5 9.5 14.2 12.2L13.5 7L12 5.5Z\"/><path d=\"M8.8 7.8L8.1 6M6 9.8L4.5 8.8M3.6 12.2H2\"/>",
  "course": "<circle cx=\"15.5\" cy=\"4.5\" r=\"2\"/><path d=\"M19.5 11L16.5 11.5L13.5 8L9.5 9L7.5 12\"/><path d=\"M13.5 8L11 13.5L14.5 16L13.5 21\"/><path d=\"M11 13.5L8.5 17H4.5\"/>",
  "crayon": "<path d=\"M4 20L5 15L16 4L20 8L9 19Z\"/><path d=\"M13.5 6.5L17.5 10.5\"/>",
  "deconnexion": "<path d=\"M12 3V11\"/><path d=\"M7 6.3A8 8 0 1 0 17 6.3\"/>",
  "disque": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><circle cx=\"12\" cy=\"12\" r=\"2.5\"/>",
  "drapeau": "<path d=\"M5 3V21\"/><rect x=\"5\" y=\"4\" width=\"14\" height=\"10\"/><path d=\"M5 9H19\" /><rect x=\"8.5\" y=\"4\" width=\"3.5\" height=\"5\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"15.5\" y=\"4\" width=\"3.5\" height=\"5\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"5\" y=\"9\" width=\"3.5\" height=\"5\" fill=\"currentColor\" stroke=\"none\"/><rect x=\"12\" y=\"9\" width=\"3.5\" height=\"5\" fill=\"currentColor\" stroke=\"none\"/>",
  "endurance": "<path d=\"M3 12H7L9.5 6L14.5 18L17 12H21\"/>",
  "fatigue": "<rect x=\"2.5\" y=\"7.5\" width=\"16.5\" height=\"9\"/><path d=\"M21.5 10.5V13.5M6 10.5V13.5\"/>",
  "flamme": "<path d=\"M12 2.5C12.5 6.5 18 8.5 18 14.5A6 6 0 0 1 6 14.5C6 11.5 8 10 9 7.5C10 9 10.5 9.5 11 10C11.5 7.5 11.5 5 12 2.5Z\"/><path d=\"M12 20.5A2.5 2.5 0 0 1 9.5 18C9.5 16.5 11 15.5 12 14C13 15.5 14.5 16.5 14.5 18A2.5 2.5 0 0 1 12 20.5Z\"/>",
  "groupe": "<circle cx=\"9\" cy=\"8\" r=\"3\"/><path d=\"M3 20V19A6 6 0 0 1 15 19V20\"/><path d=\"M15 5.3A3 3 0 0 1 15 10.7M18 14A5 5 0 0 1 21 18.5V20\"/>",
  "habitude": "<path d=\"M20 12A8 8 0 1 1 17.7 6.3\"/><path d=\"M20 3.5V7.5H16\"/><path d=\"M8.5 12L11 14.5L15.5 10\"/>",
  "hydratation": "<path d=\"M12 3L18 11A7 7 0 1 1 6 11Z\"/>",
  "info": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 11V17\"/><circle cx=\"12\" cy=\"7.6\" r=\".9\" fill=\"currentColor\" stroke=\"none\"/>",
  "intensite": "<path d=\"M4 17A8 8 0 0 1 20 17\"/><path d=\"M12 17L16 11\"/><path d=\"M3 20H21\"/>",
  "kettlebell": "<circle cx=\"12\" cy=\"15\" r=\"6\"/><path d=\"M8.5 10.2V7.5a3.5 3.5 0 0 1 7 0v2.7\"/>",
  "lune": "<path d=\"M20 14.5A8 8 0 1 1 9.5 4A6.5 6.5 0 0 0 20 14.5Z\"/>",
  "meandre": "<path d=\"M4 20V4H20V16H8V8H16V12H12\"/>",
  "menu": "<path d=\"M4 7H20M4 12H20M4 17H20\"/>",
  "message": "<path d=\"M4 5H20V16H10L6 20V16H4Z\"/>",
  "musculation": "<path d=\"M13 2L5 13.5H11L10 22L19 10H13Z\"/>",
  "nutrition": "<circle cx=\"12\" cy=\"12\" r=\"6\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M2.5 4V8.5H4.5V4M3.5 8.5V20\"/><path d=\"M21 20V4C19.5 5.5 19.5 9 19.5 12H21\"/>",
  "objectif": "<circle cx=\"10\" cy=\"14\" r=\"7.5\"/><circle cx=\"10\" cy=\"14\" r=\"3.5\"/><path d=\"M10 14L20.5 3.5M17.5 3.5V6.5H20.5\"/>",
  "performance": "<path d=\"M13 2L5 13.5H11L10 22L19 10H13Z\"/>",
  "programme": "<path d=\"M12 4L20 8L12 12L4 8Z\"/><path d=\"M4 12L12 16L20 12M4 16L12 20L20 16\"/>",
  "progression": "<path d=\"M3 20H8V15H13V10H18V5H21\"/>",
  "refresh": "<path d=\"M20 12A8 8 0 0 0 6 6.3M4 3.5V7.5H8M4 12A8 8 0 0 0 18 17.7M20 20.5V16.5H16\"/>",
  "reglages": "<path d=\"M19.05 10.11 L21.48 10.50 L21.48 13.50 L19.05 13.89 L18.32 15.65 L19.77 17.64 L17.64 19.77 L15.65 18.32 L13.89 19.05 L13.50 21.48 L10.50 21.48 L10.11 19.05 L8.35 18.32 L6.36 19.77 L4.23 17.64 L5.68 15.65 L4.95 13.89 L2.52 13.50 L2.52 10.50 L4.95 10.11 L5.68 8.35 L4.23 6.36 L6.36 4.23 L8.35 5.68 L10.11 4.95 L10.50 2.52 L13.50 2.52 L13.89 4.95 L15.65 5.68 L17.64 4.23 L19.77 6.36 L18.32 8.35Z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>",
  "repos": "<path d=\"M4 10H11L4 20H11M14 3.5H19L14 10.5H19\"/>",
  "seance": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"15\"/><path d=\"M4 10H20M8 3V7M16 3V7\"/><rect x=\"8\" y=\"13\" width=\"3\" height=\"3\"/>",
  "sommeil": "<path d=\"M3 5V20M3 13.5H21V20M3 17H21\"/><rect x=\"5.5\" y=\"9.5\" width=\"4\" height=\"4\"/><path d=\"M14 4H18L14 9H18\"/>",
  "statistiques": "<path d=\"M3 20H21M6 20V13M12 20V5M18 20V9\"/>",
  "stress": "<circle cx=\"12\" cy=\"14.5\" r=\"6.5\"/><path d=\"M12 2V4.5M5.5 4.5L7.2 6.5M18.5 4.5L16.8 6.5M8.5 16.5L10 14.5L12 17L14 14.5L15.5 16.5\"/>",
  "tempo": "<path d=\"M8 21L10.5 3H13.5L16 21Z\"/><path d=\"M12 15L17 7\"/>",
  "test": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><circle cx=\"12\" cy=\"12\" r=\"4.5\"/><circle cx=\"12\" cy=\"12\" r=\"1\" fill=\"currentColor\"/>",
  "trophee": "<path d=\"M7 4H17V10A5 5 0 0 1 7 10Z\"/><path d=\"M7 6H4V8A3 3 0 0 0 7.3 11M17 6H20V8A3 3 0 0 1 16.7 11M12 15V18\"/><path d=\"M8 18H16V21H8Z\"/>",
  "wellness": "<path d=\"M12 20L4.4 12.4A4.6 4.6 0 0 1 12 6.9A4.6 4.6 0 0 1 19.6 12.4Z\"/><path d=\"M7.5 12.5H10L11 10.5L13 14.5L14 12.5H16.5\"/>",
};

PATHS["medaille"] = PATHS["trophee"];
PATHS["graphique"] = PATHS["statistiques"];
PATHS["coeur"] = PATHS["coeur"] ?? PATHS["wellness"];

export type AgonIconName = keyof typeof PATHS;

interface AgonIconProps {
  name: AgonIconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}

export function AgonIcon({ name, size = 20, strokeWidth = 1.5, className, style }: AgonIconProps) {
  const html = PATHS[name];
  if (!html) return null;
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="square"
      strokeLinejoin="miter"
      aria-hidden="true"
      className={className}
      style={style}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export const EMOJI_TO_ICON: Record<string, AgonIconName> = {
  "\u{1F4AA}": "musculation", "\u{1F3CB}\u{FE0F}": "musculation", "\u{1F3CB}": "musculation",
  "\u{1F3C3}": "course", "\u{1F6B6}": "course",
  "\u{23F1}\u{FE0F}": "chrono", "\u{23F1}": "chrono", "\u{23F2}\u{FE0F}": "chrono", "\u{23F2}": "chrono",
  "\u{1F634}": "sommeil", "\u{1F6CC}": "sommeil",
  "\u{1F319}": "lune",
  "\u{1F4A4}": "repos",
  "\u{1F4A7}": "hydratation", "\u{1F9F4}": "hydratation",
  "\u{1F37D}\u{FE0F}": "nutrition", "\u{1F37D}": "nutrition", "\u{1F957}": "nutrition", "\u{1F34E}": "nutrition",
  "\u{1F525}": "flamme",
  "\u{2764}\u{FE0F}": "coeur", "\u{2764}": "coeur",
  "\u{1F9D8}": "wellness", "\u{1F33F}": "wellness", "\u{1F48A}": "wellness",
  "\u{26A1}": "intensite", "\u{2600}\u{FE0F}": "intensite", "\u{2600}": "intensite",
  "\u{1F3AF}": "objectif",
  "\u{1F4CA}": "statistiques",
  "\u{1F4C8}": "progression", "\u{26F7}\u{FE0F}": "progression", "\u{26F7}": "progression",
  "\u{1F4C5}": "calendrier",
  "\u{1F4AC}": "commentaire",
  "\u{1F514}": "cloche",
  "\u{1F9E0}": "cerveau",
  "\u{1F630}": "stress", "\u{1F624}": "stress",
  "\u{1F62B}": "fatigue",
  "\u{1F6A9}": "drapeau", "\u{1F3C1}": "drapeau",
  "\u{2696}\u{FE0F}": "balance", "\u{2696}": "balance",
  "\u{1F4CF}": "biometrie",
  "\u{1F5D1}\u{FE0F}": "corbeille", "\u{1F5D1}": "corbeille",
  "\u{270F}\u{FE0F}": "crayon", "\u{270F}": "crayon", "\u{270D}\u{FE0F}": "crayon", "\u{270D}": "crayon",
  "\u{2139}\u{FE0F}": "info", "\u{2139}": "info",
  "\u{1F504}": "refresh", "\u{1F9F9}": "refresh",
  "\u{1F4CB}": "clipboard", "\u{1F4D6}": "clipboard",
  "\u{2699}\u{FE0F}": "reglages", "\u{2699}": "reglages",
  "\u{1F3E0}": "accueil",
  "\u{1F464}": "athlete",
  "\u{1F465}": "groupe",
  "\u{26A0}\u{FE0F}": "alerte", "\u{26A0}": "alerte",
  "\u{1F3C6}": "trophee",
  "\u{1F947}": "medaille", "\u{1F948}": "medaille", "\u{1F949}": "medaille", "\u{1F3C5}": "medaille",
  "\u{1F6B4}": "endurance", "\u{1F3CA}": "endurance",
  "\u{1F3BE}": "performance",
  "\u{1F3B5}": "tempo",
  "\u{1F305}": "habitude",
};

interface EmojiIconProps {
  value: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}

export function EmojiIcon({ value, size = 20, strokeWidth = 1.5, className, style }: EmojiIconProps) {
  // Direct icon name
  if (value in PATHS) {
    return <AgonIcon name={value as AgonIconName} size={size} strokeWidth={strokeWidth} className={className} style={style} />;
  }
  // Emoji lookup
  const mapped = EMOJI_TO_ICON[value];
  if (mapped) {
    return <AgonIcon name={mapped} size={size} strokeWidth={strokeWidth} className={className} style={style} />;
  }
  // Fallback: render as text
  return <span className={className} style={{ fontSize: size, lineHeight: 1, ...style }}>{value}</span>;
}
